"""update_meta_fields_default_value

Revision ID: 09022e735282
Revises: 60fa0004b3f6
Create Date: 2025-10-17 11:28:56.857901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09022e735282'
down_revision: Union[str, Sequence[str], None] = '60fa0004b3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 更新现有记录的 meta_fields 为 {} (如果为 NULL)
    op.execute("""
        UPDATE documents 
        SET meta_fields = '{}' 
        WHERE meta_fields IS NULL
    """)
    
    # 更新现有记录的 parser_config 为 {} (如果为 NULL)
    op.execute("""
        UPDATE documents 
        SET parser_config = '{}' 
        WHERE parser_config IS NULL
    """)
    
    # 设置 meta_fields 列的默认值
    op.alter_column('documents', 'meta_fields',
                    existing_type=sa.JSON(),
                    server_default='{}',
                    comment='文档元数据字段(JSON)')
    
    # 设置 parser_config 列的默认值
    op.alter_column('documents', 'parser_config',
                    existing_type=sa.JSON(),
                    server_default='{}',
                    comment='解析器配置(JSON)')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 移除默认值
    op.alter_column('documents', 'meta_fields',
                    existing_type=sa.JSON(),
                    server_default=None,
                    comment='文档元数据字段(JSON)')
    
    op.alter_column('documents', 'parser_config',
                    existing_type=sa.JSON(),
                    server_default=None,
                    comment='解析器配置(JSON)')
    
    # ### end Alembic commands ###
