"""Initial migration

Revision ID: 3f9c6f6e03d6
Revises: 
Create Date: 2025-09-29 10:50:17.813465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9c6f6e03d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgebase',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('language', sa.String(length=32), nullable=True, comment='English|Chinese'),
    sa.Column('owner_id', sa.String(length=32), nullable=False, comment='所有者用户ID'),
    sa.Column('tenant_id', sa.String(length=32), nullable=True, comment='所属租户ID'),
    sa.Column('doc_num', sa.Integer(), nullable=True),
    sa.Column('embd_provider_name', sa.String(length=32), nullable=True, comment='默认嵌入模型供应商名称'),
    sa.Column('embd_model_name', sa.String(length=32), nullable=True, comment='默认嵌入模型名称'),
    sa.Column('rerank_provider_name', sa.String(length=32), nullable=True, comment='默认重排序模型供应商名称'),
    sa.Column('rerank_model_name', sa.String(length=32), nullable=True, comment='默认重排序模型名称'),
    sa.Column('parser_id', sa.String(length=32), nullable=False, comment='解析器类型'),
    sa.Column('parser_config', sa.JSON(), nullable=False, comment='解析器配置(JSON格式)'),
    sa.Column('page_rank', sa.Integer(), nullable=True, comment='页面排名'),
    sa.Column('status', sa.String(length=1), nullable=True, comment='状态(0:无效, 1:有效)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebase_doc_num'), 'knowledgebase', ['doc_num'], unique=False)
    op.create_index(op.f('ix_knowledgebase_embd_model_name'), 'knowledgebase', ['embd_model_name'], unique=False)
    op.create_index(op.f('ix_knowledgebase_embd_provider_name'), 'knowledgebase', ['embd_provider_name'], unique=False)
    op.create_index(op.f('ix_knowledgebase_language'), 'knowledgebase', ['language'], unique=False)
    op.create_index(op.f('ix_knowledgebase_name'), 'knowledgebase', ['name'], unique=False)
    op.create_index(op.f('ix_knowledgebase_owner_id'), 'knowledgebase', ['owner_id'], unique=False)
    op.create_index(op.f('ix_knowledgebase_rerank_model_name'), 'knowledgebase', ['rerank_model_name'], unique=False)
    op.create_index(op.f('ix_knowledgebase_rerank_provider_name'), 'knowledgebase', ['rerank_provider_name'], unique=False)
    op.create_index(op.f('ix_knowledgebase_status'), 'knowledgebase', ['status'], unique=False)
    op.create_index(op.f('ix_knowledgebase_tenant_id'), 'knowledgebase', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='租户名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='租户描述'),
    sa.Column('owner_id', sa.String(length=32), nullable=False, comment='租户Owner用户ID'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='租户成员数量'),
    sa.Column('status', sa.String(length=1), nullable=False, comment='状态(0:无效, 1:有效)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_member_count'), 'tenants', ['member_count'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_owner_id'), 'tenants', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False, comment='文档ID'),
    sa.Column('kb_id', sa.String(length=36), nullable=False, comment='知识库ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文档名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='文档描述'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='文档类型'),
    sa.Column('suffix', sa.String(length=10), nullable=True, comment='文件扩展名'),
    sa.Column('file_id', sa.String(length=500), nullable=True, comment='文件唯一标识符'),
    sa.Column('size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('parser_id', sa.String(length=50), nullable=False, comment='解析器类型'),
    sa.Column('parser_config', sa.Text(), nullable=True, comment='解析器配置(JSON)'),
    sa.Column('thumbnail_id', sa.String(length=500), nullable=True, comment='缩略图ID'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='文件来源'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledgebase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_members',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('joined_at', sa.DateTime(), nullable=False, comment='加入时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )
    op.create_table('file2document',
    sa.Column('id', sa.String(length=36), nullable=False, comment='关联ID'),
    sa.Column('file_id', sa.String(length=36), nullable=False, comment='文件ID'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='文档ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file2document')
    op.drop_table('tenant_members')
    op.drop_table('documents')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_owner_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_member_count'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_knowledgebase_tenant_id'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_status'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_rerank_provider_name'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_rerank_model_name'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_owner_id'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_name'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_language'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_embd_provider_name'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_embd_model_name'), table_name='knowledgebase')
    op.drop_index(op.f('ix_knowledgebase_doc_num'), table_name='knowledgebase')
    op.drop_table('knowledgebase')
    # ### end Alembic commands ###
