"""add_meta_fields_to_documents

Revision ID: 60fa0004b3f6
Revises: 8e0bfa523570
Create Date: 2025-10-17 11:16:55.952836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fa0004b3f6'
down_revision: Union[str, Sequence[str], None] = '8e0bfa523570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('meta_fields', sa.JSON(), nullable=True, comment='文档元数据字段(JSON)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'meta_fields')
    # ### end Alembic commands ###
